export const expenseTypes = [
  { value: "CASH_LOADERS", label: "Cash Loaders" },
  { value: "CLAIMABLES_PAYMENT", label: "Claimables - Payment" },
  { value: "CLEANING_ITEMS", label: "Cleaning Items" },
  { value: "CONSULTANCY_CHARGES", label: "Consultancy Charges" },
  { value: "CONTAINER_UNLOADING_CHARGES", label: "Container Unloading Charges" },
  { value: "COOLER_RENTAL", label: "Cooler Rental" },
  { value: "COURIER_CHARGES", label: "Courier Charges" },
  { value: "DAILY_KITCHEN_EXP", label: "Daily Kitchen Exp." },
  { value: "DMS_PAYMENT", label: "DMS - Payment" },
  { value: "ELECTRICITY_BILL", label: "Electricity Bill" },
  { value: "EMPLOYEE_ACCOMODATION_EXP", label: "Employee Accomodation Exp." },
  { value: "EMPLOYEE_MOBILE_EXP", label: "Employee Mobile Exp." },
  { value: "EMPLOYEE_TRAVELLING_EXP", label: "Employee Travelling Exp." },
  { value: "EMPTY_SORTING", label: "Empty Sorting" },
  { value: "ENTERTAINMENT", label: "Entertainment" },
  { value: "EOBI", label: "EOBI" },
  { value: "FUEL_FOR_BIKE", label: "Fuel For Bike" },
  { value: "GAS_BILL", label: "Gas Bill" },
  { value: "INTERNET_BILL", label: "Internet Bill" },
  { value: "LEGAL_CHARGES", label: "Legal Charges" },
  { value: "LOADERS_ACCOUMODATION_EXP", label: "Loaders Accoumodation Exp." },
  { value: "LOADING_CHARGES", label: "Loading Charges" },
  { value: "MEETING_EXP", label: "Meeting Exp." },
  { value: "PACKING_MATERIAL", label: "Packing Material" },
  { value: "PRINTER_SERVICE", label: "Printer Service" },
  { value: "PRINTING_STATIONERY", label: "Printing & Stationery" },
  { value: "REPAIR_MAINT_GENERAL", label: "Repair & Maint. General" },
  { value: "REPAIR_MAINT_VEHICLE", label: "Repair & Maint. Vehicle" },
  { value: "REPAIR_MAINT_WAREHOUSE", label: "Repair & Maint. Warehouse" },
  { value: "RIKSHAW_RENTAL", label: "Rikshaw Rental" },
  { value: "SECP_FEE", label: "SECP Fee" },
  { value: "SECURITY_CAMERA_SERVICE", label: "Security Camera Service" },
  { value: "TAX_PAYMENT", label: "Tax Payment" },
  { value: "TOLLS_TAXES", label: "Tolls & Taxes" },
  { value: "TRAFFIC_POLICE", label: "Traffic Police" },
  { value: "VEHICLE_CHALLAN", label: "Vehicle Challan" },
  { value: "VEHICLE_FUEL", label: "Vehicle Fuel" },
  { value: "VEHICLE_RENTAL", label: "Vehicle Rental" },
  { value: "VEHICLES_RENT", label: "Vehicles Rent" },
  { value: "WAREHOUSE_RENT", label: "Warehouse Rent" },
  { value: "WORKER_WELFARE", label: "Worker Welfare" },
  { value: "INVESTOR_PAYMENT", label: "Investor Payment" },
  { value: "VEHICLE_PARKING", label: "Vehicle Parking" },
  { value: "VEHICLE_PASSING", label: "Vehicle Passing" },
  { value: "GUARD_TEA_EXP", label: "Guard Tea Exp." },
  { value: "GARBAGE_COLLECTION", label: "Garbage Collection" },
  { value: "FIXED_ASSET", label: "Fixed Asset" },
  { value: "INCENTIVE_PAYMENT", label: "Incentive Payment" },
];
