export const DESIGNATIONS_BY_DEPARTMENT: Record<string, string[]> = {
  FINANCE: [
    "ACCOUNTANT",
    "ACCOUNTS MANAGER",
    "ACCOUNTS OFFICER",
    "ACCOUNTS SUPERVISOR",
    "ASST ACCOUNTS MANAGER",
    "ASST. CASHIER",
    "CASHIER",
    "CFO",
    "RUNNER",
  ],
  HR: ["ASST ADMIN", "HR & ADMIN SUPERVISOR"],
  WAREHOUSE: ["ASST. STORE KEEPER", "GROUP WAREHOUSE SUPERVISOR", "STORE KEEPER"],
  SALES: [
    "BDO",
    "DELIVERY MAN",
    "DISTRIBUTION MANAGER",
    "DSF",
    "ORDER BOOKER",
    "ORDER BOOKER - LMT",
    "PSO",
    "SALE SUPERVISOR",
    "SALESMAN",
    "SALESMAN + DRIVER",
    "SALESMAN GT",
    "SALESMAN LMT",
    "SALESMAN WS",
    "SALESMAN WS & BAKERIES",
    "SPARE PSO",
    "SUPERVISOR",
  ],
  "SALES ADMIN": ["BUSINESS KPO", "D.V.O", "KPO"],
  MANAGEMENT: ["BUSINESS MANAGER", "DIRECTOR", "GENERAL MANANGER"],
  CREDIT: ["CREDIT CONTROLLER", "DEO", "RECOVERY OFFICER"],
  LOGISTICS: ["ELECTRICAN", "LIFTER", "LOGISTIC MANAGER", "MECHANIC"],
  ADMINISTRATION: [
    "GARDNER",
    "OFFICE BOY",
    "OFFICE BOY + SWEEPER",
    "SECURITY GUARD",
    "SECURITY SUPERVISOR",
    "SWEEPER",
  ],
  LOADERS: ["LOADER SUPERVISER", "PACKER"],
  OPERATIONS: ["OPERATIONS MANAGER"],
};

export const DEPARTMENTS = Object.keys(DESIGNATIONS_BY_DEPARTMENT);
export const ALL_DESIGNATIONS = Object.values(DESIGNATIONS_BY_DEPARTMENT).flat();

export const EMPLOYMENT_STATUSES = [
  "Active:Working",
  "Inactive:Terminated",
  "Inactive:Resigned",
  "Inactive:Absent without information",
];
