export const mockEmployees = [
  {
    id: "1",
    employeeName: "Employee EMP001",
    employeeId: "EMP001",
    position: "Frontend Developer",
    department: "Engineering",
    email: "emp001@example.com",
    phone: "",
    joinDate: "2023-05-01",
    status: "Active",
    avatar: "/placeholder.svg?height=40&width=40",
    birthDate: "1990-04-15",
    address: "",
    emergencyContact: "",
    bloodGroup: "O+",
    employeeType: "Full-time",
    manager: "",
    salary: "PKR 95,000",
    skills: ["React", "TypeScript", "CSS", "HTML", "JavaScript"],
    education: [
      {
        degree: "BSc Computer Science",
        institution: "Stanford University",
        year: "2012",
      },
      {
        degree: "MSc Web Development",
        institution: "UC Berkeley",
        year: "2014",
      },
    ],
    documents: [
      { name: "Resume.pdf", uploadDate: "2023-05-01" },
      { name: "Contract.pdf", uploadDate: "2023-05-01" },
      { name: "ID.jpg", uploadDate: "2023-05-01" },
    ],
    reviews: [
      {
        title: "Annual Performance Review",
        rating: 4.5,
        comments: "Consistently delivering high-quality work.",
        reviewer: "",
        date: "2023-04-01",
      },
      {
        title: "Project Evaluation",
        rating: 4.8,
        comments: "Outstanding contribution to the website redesign project.",
        reviewer: "",
        date: "2023-02-15",
      },
    ],
    achievements: [
      {
        title: "Employee of the Month",
        description: "Recognized for outstanding performance and dedication.",
        date: "2023-03",
      },
      {
        title: "Project Excellence Award",
        description: "For exceptional contribution to the mobile app launch.",
        date: "2023-01",
      },
    ],
  },
  {
    id: "2",
    employeeName: "Employee EMP002",
    employeeId: "EMP002",
    position: "Marketing Specialist",
    department: "Marketing",
    email: "emp002@example.com",
    phone: "",
    joinDate: "2023-04-15",
    status: "On Leave",
    avatar: "/placeholder.svg?height=40&width=40",
  },
  {
    id: "3",
    employeeName: "Employee EMP003",
    employeeId: "EMP003",
    position: "HR Manager",
    department: "Human Resources",
    email: "emp003@example.com",
    phone: "",
    joinDate: "2023-04-10",
    status: "Active",
    avatar: "/placeholder.svg?height=40&width=40",
  },
  {
    id: "4",
    employeeName: "Employee EMP004",
    employeeId: "EMP004",
    position: "Backend Developer",
    department: "Engineering",
    email: "emp004@example.com",
    phone: "",
    joinDate: "2023-04-05",
    status: "Remote",
    avatar: "/placeholder.svg?height=40&width=40",
  },
  {
    id: "5",
    employeeName: "Employee EMP005",
    employeeId: "EMP005",
    position: "UX Designer",
    department: "Design",
    email: "emp005@example.com",
    phone: "",
    joinDate: "2023-03-20",
    status: "Active",
    avatar: "/placeholder.svg?height=40&width=40",
  },
  {
    id: "6",
    employeeName: "Employee EMP006",
    employeeId: "EMP006",
    position: "Financial Analyst",
    department: "Finance",
    email: "emp006@example.com",
    phone: "",
    joinDate: "2023-03-15",
    status: "Active",
    avatar: "/placeholder.svg?height=40&width=40",
  },
  {
    id: "7",
    employeeName: "Employee EMP007",
    employeeId: "EMP007",
    position: "Sales Representative",
    department: "Sales",
    email: "emp007@example.com",
    phone: "",
    joinDate: "2023-03-10",
    status: "Active",
    avatar: "/placeholder.svg?height=40&width=40",
  },
  {
    id: "8",
    employeeName: "Employee EMP008",
    employeeId: "EMP008",
    position: "Operations Manager",
    department: "Operations",
    email: "emp008@example.com",
    phone: "",
    joinDate: "2023-03-05",
    status: "On Leave",
    avatar: "/placeholder.svg?height=40&width=40",
  },
  {
    id: "9",
    employeeName: "Employee EMP009",
    employeeId: "EMP009",
    position: "Content Writer",
    department: "Marketing",
    email: "emp009@example.com",
    phone: "",
    joinDate: "2023-02-25",
    status: "Active",
    avatar: "/placeholder.svg?height=40&width=40",
  },
  {
    id: "10",
    employeeName: "Employee EMP010",
    employeeId: "EMP010",
    position: "DevOps Engineer",
    department: "Engineering",
    email: "emp010@example.com",
    phone: "",
    joinDate: "2023-02-20",
    status: "Remote",
    avatar: "/placeholder.svg?height=40&width=40",
  },
];

export const mockAttendance = [
  {
    id: "1",
    employeeId: "EMP001",
    employeeName: "Employee EMP001",
    date: "2023-05-01",
    checkIn: "09:00 AM",
    checkOut: "06:00 PM",
    checkInStatus: "on-time",
    checkOutStatus: "on-time",
    workingHours: "9.0",
    status: "Present",
  },
  {
    id: "2",
    employeeId: "EMP002",
    employeeName: "Employee EMP002",
    date: "2023-05-01",
    checkIn: "09:30 AM",
    checkOut: "05:30 PM",
    checkInStatus: "late",
    checkOutStatus: "on-time",
    workingHours: "8.0",
    status: "Present",
  },
  {
    id: "3",
    employeeId: "EMP003",
    employeeName: "Employee EMP003",
    date: "2023-05-01",
    checkIn: "08:45 AM",
    checkOut: "05:45 PM",
    checkInStatus: "on-time",
    checkOutStatus: "on-time",
    workingHours: "9.0",
    status: "Present",
  },
  {
    id: "4",
    employeeId: "EMP004",
    employeeName: "Employee EMP004",
    date: "2023-05-01",
    checkIn: "09:15 AM",
    checkOut: "04:30 PM",
    checkInStatus: "on-time",
    checkOutStatus: "early",
    workingHours: "7.25",
    status: "Present",
  },
  {
    id: "5",
    employeeId: "EMP005",
    employeeName: "Employee EMP005",
    date: "2023-05-01",
    checkIn: "",
    checkOut: "",
    checkInStatus: "",
    checkOutStatus: "",
    workingHours: "0",
    status: "Absent",
  },
  {
    id: "6",
    employeeId: "EMP001",
    employeeName: "Employee EMP001",
    date: "2023-04-30",
    checkIn: "08:55 AM",
    checkOut: "06:05 PM",
    checkInStatus: "on-time",
    checkOutStatus: "on-time",
    workingHours: "9.17",
    status: "Present",
  },
  {
    id: "7",
    employeeId: "EMP002",
    employeeName: "Employee EMP002",
    date: "2023-04-30",
    checkIn: "09:00 AM",
    checkOut: "01:00 PM",
    checkInStatus: "on-time",
    checkOutStatus: "early",
    workingHours: "4.0",
    status: "Half Day",
  },
  {
    id: "8",
    employeeId: "EMP003",
    employeeName: "Employee EMP003",
    date: "2023-04-30",
    checkIn: "08:50 AM",
    checkOut: "05:50 PM",
    checkInStatus: "on-time",
    checkOutStatus: "on-time",
    workingHours: "9.0",
    status: "Present",
  },
  {
    id: "9",
    employeeId: "EMP004",
    employeeName: "Employee EMP004",
    date: "2023-04-30",
    checkIn: "09:10 AM",
    checkOut: "06:10 PM",
    checkInStatus: "on-time",
    checkOutStatus: "on-time",
    workingHours: "9.0",
    status: "Present",
  },
  {
    id: "10",
    employeeId: "EMP005",
    employeeName: "Employee EMP005",
    date: "2023-04-30",
    checkIn: "09:05 AM",
    checkOut: "06:00 PM",
    checkInStatus: "on-time",
    checkOutStatus: "on-time",
    workingHours: "8.92",
    status: "Present",
  },
];

export const mockLeaveRequests = [
  {
    id: "1",
    employeeId: "EMP001",
    employeeName: "Employee EMP001",
    leaveType: "Vacation",
    startDate: "2023-05-10",
    endDate: "2023-05-15",
    days: 6,
    reason: "Family vacation",
    status: "Pending",
  },
  {
    id: "2",
    employeeId: "EMP002",
    employeeName: "Employee EMP002",
    leaveType: "Sick Leave",
    startDate: "2023-05-03",
    endDate: "2023-05-04",
    days: 2,
    reason: "Not feeling well",
    status: "Approved",
  },
  {
    id: "3",
    employeeId: "EMP003",
    employeeName: "Employee EMP003",
    leaveType: "Personal",
    startDate: "2023-05-08",
    endDate: "2023-05-08",
    days: 1,
    reason: "Personal appointment",
    status: "Approved",
  },
  {
    id: "4",
    employeeId: "EMP004",
    employeeName: "Employee EMP004",
    leaveType: "Vacation",
    startDate: "2023-05-20",
    endDate: "2023-05-27",
    days: 8,
    reason: "Summer vacation",
    status: "Pending",
  },
  {
    id: "5",
    employeeId: "EMP005",
    employeeName: "Employee EMP005",
    leaveType: "Unpaid Leave",
    startDate: "2023-05-15",
    endDate: "2023-05-19",
    days: 5,
    reason: "Family emergency",
    status: "Rejected",
  },
  {
    id: "6",
    employeeId: "EMP006",
    employeeName: "Employee EMP006",
    leaveType: "Sick Leave",
    startDate: "2023-05-05",
    endDate: "2023-05-05",
    days: 1,
    reason: "Doctor's appointment",
    status: "Approved",
  },
  {
    id: "7",
    employeeId: "EMP007",
    employeeName: "Employee EMP007",
    leaveType: "Personal",
    startDate: "2023-05-12",
    endDate: "2023-05-12",
    days: 1,
    reason: "Personal reasons",
    status: "Pending",
  },
  {
    id: "8",
    employeeId: "EMP008",
    employeeName: "Employee EMP008",
    leaveType: "Vacation",
    startDate: "2023-05-01",
    endDate: "2023-05-05",
    days: 5,
    reason: "Spring break",
    status: "Approved",
  },
  {
    id: "9",
    employeeId: "EMP009",
    employeeName: "Employee EMP009",
    leaveType: "Sick Leave",
    startDate: "2023-05-02",
    endDate: "2023-05-03",
    days: 2,
    reason: "Feeling unwell",
    status: "Approved",
  },
  {
    id: "10",
    employeeId: "EMP010",
    employeeName: "Employee EMP010",
    leaveType: "Personal",
    startDate: "2023-05-18",
    endDate: "2023-05-19",
    days: 2,
    reason: "Family event",
    status: "Pending",
  },
];

export const mockProjects = [
  {
    id: "1",
    name: "Website Redesign",
    client: "Acme Corporation",
    startDate: "2023-04-01",
    deadline: "2023-06-30",
    team: ["EMP001", "EMP004", "EMP005"],
    progress: 65,
    status: "In Progress",
  },
  {
    id: "2",
    name: "Mobile App Development",
    client: "TechStart Inc.",
    startDate: "2023-03-15",
    deadline: "2023-07-15",
    team: ["EMP004", "EMP010"],
    progress: 40,
    status: "In Progress",
  },
  {
    id: "3",
    name: "Marketing Campaign",
    client: "GreenLife Products",
    startDate: "2023-04-10",
    deadline: "2023-05-10",
    team: ["EMP002", "EMP009", "EMP007"],
    progress: 85,
    status: "In Progress",
  },
  {
    id: "4",
    name: "HR System Implementation",
    client: "Internal",
    startDate: "2023-02-01",
    deadline: "2023-04-30",
    team: ["EMP003", "EMP008"],
    progress: 100,
    status: "Completed",
  },
  {
    id: "5",
    name: "Financial Reporting Tool",
    client: "Global Finance Ltd.",
    startDate: "2023-03-01",
    deadline: "2023-05-31",
    team: ["EMP006", "EMP001"],
    progress: 75,
    status: "In Progress",
  },
  {
    id: "6",
    name: "E-commerce Platform",
    client: "ShopEasy",
    startDate: "2023-01-15",
    deadline: "2023-04-15",
    team: ["EMP001", "EMP004", "EMP005", "EMP010"],
    progress: 100,
    status: "Completed",
  },
  {
    id: "7",
    name: "CRM Integration",
    client: "SalesForce Pro",
    startDate: "2023-04-05",
    deadline: "2023-06-05",
    team: ["EMP007", "EMP002"],
    progress: 30,
    status: "In Progress",
  },
  {
    id: "8",
    name: "Data Migration",
    client: "DataSafe Inc.",
    startDate: "2023-03-20",
    deadline: "2023-05-20",
    team: ["EMP010", "EMP004"],
    progress: 50,
    status: "On Hold",
  },
  {
    id: "9",
    name: "Social Media Strategy",
    client: "BrandBoost",
    startDate: "2023-04-15",
    deadline: "2023-05-15",
    team: ["EMP009", "EMP002"],
    progress: 60,
    status: "In Progress",
  },
  {
    id: "10",
    name: "Office Relocation",
    client: "Internal",
    startDate: "2023-02-15",
    deadline: "2023-03-31",
    team: ["EMP008", "EMP003", "EMP006"],
    progress: 100,
    status: "Completed",
  },
];
